---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: django-jsonapi-training
  annotations:
    github.com/project-slug: columbia-it/django-jsonapi-training
    backstage.io/techdocs-ref: 'url:https://github.com/columbia-it/django-jsonapi-training'
spec:
  type: website
  lifecycle: production
  owner: alan@columbia.edu
  definition:
    $text: https://github.com/columbia-it/django-jsonapi-training/blob/master/docs/schemas/openapi.yaml
